development:
  adapter: postgresql
  encoding: unicode
  database: homewrkr_development
  pool: 5
  username: josephwaine
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: homewrkr_test
  pool: 5
  username: josephwaine
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: homewrkr_production
  pool: 5
  username: josephwaine
  password:
